---
title: "TidyTuesday - Tour de France"
author: "Shemaiah S. Sotrah"
date: "4/8/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gganimate)
library(gifski)
```

## Load Data

```{r, message=FALSE}
tdf_winners <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-07/tdf_winners.csv')

stage_data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-07/stage_data.csv')

tdf_stages <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-07/tdf_stages.csv')

head(tdf_winners)
head(stage_data)
head(tdf_stages)
```

## Manipulate Data

```{r, message=FALSE}
 stage_data %>%
  filter(year %in% c("2002", "2003"),
         rider %in% c("O'Grady Stuart", "Armstrong Lance")) %>%
  separate(time, into = c("number", "label"), sep = "S") %>% 
  separate(stage_results_id, into = c("label", "stage"), sep = "-") %>%
  select(- label) %>%
  mutate(number = as.numeric(number)) %>%
  mutate(stage = factor(stage, levels = c("0", "1","2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20")))-> winner
```

## Visualize Data

```{r, fig.width= 9, fig.height= 5}
ggplot(winner, aes(x = stage, y = number)) +
  geom_point(aes(color = rider)) +
  facet_wrap(~year) +
  theme(axis.text = element_text(angle = 90)) +
  theme_bw() +
  scale_color_manual(values = c("chocolate2", "cadetblue4")) +
  labs(x = "Race Stage",
       y = "Time (sec)",
       color = "Rider",
       title = "Race Time Comparison for Tour de France",
       subtitle = "2002 and 2003") -> plot_winner

 plot_winner + 
  transition_states(stage, transition_length = 20, state_length = 25) 
```





