---
title: "TidyTuesday Volcano Eruptions"
author: "Shemaiah S. Sotrah"
date: "5/10/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
```

## Loading Data

```{r, message=F}
volcano <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/volcano.csv')
eruptions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/eruptions.csv')
events <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/events.csv')

```

## Visualize Data

```{r}
ggplot(volcano, aes(x = elevation, y = primary_volcano_type, fill = primary_volcano_type )) +
  geom_density_ridges() +
  theme_classic() +
  labs(y = "primary volcano type", fill = "primary volcano type" ) -> pp

pp
ggsave("volcano.png", plot = pp, width = 6, height = 9)
```

## Explanation

GGridges is a fun library to use when you want to easily compare the distribution of multiples. It is also incredibly straightforward since it can easily be used with ggplot2. Here, I used it to compare the elevation of several primary volcano types. 